### ISSUE TITLE
Add option to sites for specifying the root context path

### ISSUE THREAD

**Issue by clockard** [connexta/replication#77]
**Describe the task**
Add option to sites for specifying the root context path. This will allow replication to work with sites that have changed their root context to something other than the default context of 'services'

**Comment by peterhuffer** [comment]
We can close this right?

**Comment by peterhuffer** [comment]
Master port: https://github.com/connexta/replication/commit/3dbf6ba57d0b68f1a797919f325dc2a47d7d2c4a
