### ISSUE TITLE
Replicator thread can stop due to runtime exception

### ISSUE THREAD

**Issue by peterhuffer** [connexta/replication#84]
**Describe the bug**
Replication stops working. When solr is not initially available and the history attempts to save, a runtime exception is thrown that is not caught and interrupts the replicator thread.

See: https://github.com/connexta/replication/blob/0.2.x/replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorImpl.java#L203 

**Affects version**
0.2.2

**To Reproduce**
This is a timing issue that only occurs sometimes after startup and a replication configuration runs before solr is available.

**Expected behavior**
The replicator thread will never stop running.

**Comment by clockard** [comment]
This was already fixed in REP-66. Closing.
